build with jdk8 to bypass issue below when publish updatesite to bintray: Caused by: java.lang.NoClassDefFoundError: java/util/function/Consumer   at groovyx.net.http.EncoderRegistry.buildDefaultEncoderMap(EncoderRegistry.java:349)   at groovyx.net.http.EncoderRegistry.<init>(EncoderRegistry.java:91)   at com.jfrog.bintray.gradle.BintrayHttpClientFactory$1.<init>(BintrayHttpClientFactory.groovy)   at com.jfrog.bintray.gradle.BintrayHttpClientFactory.create(BintrayHttpClientFactory.groovy:41)   at com.jfrog.bintray.gradle.BintrayHttpClientFactory$create.call(Unknown Source)